# Generated by Django 4.0.1 on 2023-02-22 06:51

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[users.validators.date_of_birth_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Domain rambler.ru is prohibit', regex='@rambler.ru')]),
        ),
    ]
